jQuery(document).ready(function($){
    $('#h1color').wpColorPicker();
    $('#h2color').wpColorPicker();
    $('#h3color').wpColorPicker();
    $('#h4color').wpColorPicker();
    $('#pcolor').wpColorPicker();
    $('#linkcolor').wpColorPicker();
    $('#labelcolor').wpColorPicker();
    $('#linkhovercolor').wpColorPicker();
});